### ISSUE TITLE
convert_annoset with error

### ISSUE THREAD

**Issue by embedeepLHY** [eric612/CityPersonsOnRoad#1]
/home/lhy/work/DL_Project/mobileYOLO_Seg/MobileNet-YOLO/tools/convert_annoset --anno_type=detection_with_segmentation --label_type=xml --label_map_file=/home/lhy/work/DL_Project/mobileYOLO_Seg/MobileNet-YOLO/data/cityscapes/../../data/cityscapes/labelmap.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False ./data/ /home/lhy/work/DL_Project/mobileYOLO_Seg/MobileNet-YOLO/data/cityscapes/../../data/cityscapes/val.txt ./data/cityscapes/lmdb/cityscapes_val_lmdb
Traceback (most recent call last):
  File "/home/lhy/work/DL_Project/mobileYOLO_Seg/MobileNet-YOLO/data/cityscapes/../../scripts/create_annoset.py", line 184, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Hi~ any ideal why error？

**Comment by eric612** [comment]
Did the create_list.sh work correct ? Check the all files was exist in train.txt , val.txt

**Comment by embedeepLHY** [comment]
Thanks for your reply, we find the error is missing the "/tools/convert_annoset". We will try to compile this tool, thanks again！
